version: '3.3'

services:
  postgres:
    container_name: postgres-service
    image: postgres:13
    environment:
      - POSTGRES_DB=storeapp
      - POSTGRES_USER=storeuser
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-service
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
