version: '3.3'

services:
  postgres:
    container_name: postgres-service
    image: postgres:13
    environment:
      - POSTGRES_DB=storeapp
      - POSTGRES_USER=storeuser
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-service
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80

  mysql:
    container_name: mysql-service
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ONETIME_PASSWORD=yes
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=storeuser
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=storeapp
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysqlql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql # name of mysql service
    ports:
      - 8080:80
